apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-taqi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-taqi
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-taqi
  namespace: user1-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-taqi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-taqi
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/user1-tenant/my-app/devfile-sample-taqi@sha256:1d69cf2f1ab0f8bad21e3cfa1144be0301695d9f4f4e8019211d8b930d8a2576
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
